// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Layer: typeof import('./src/components/layer/index.vue')['default']
    Mv_popup: typeof import('./src/components/mv_popup/index.vue')['default']
    Popupcpm: typeof import('./src/components/layer/popupcpm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/layer/Test.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanLoading: typeof import('vant/es')['Loading']
    VanPopup: typeof import('vant/es')['Popup']
  }
}
